CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE USER DB_USER WITH ENCRYPTED PASSWORD 'DB_PASS' CREATEDB;
CREATE DATABASE workshops_test OWNER=DB_USER ENCODING 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8';
CREATE DATABASE workshops_development OWNER=DB_USER ENCODING 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8';
CREATE DATABASE workshops_production OWNER=DB_USER ENCODING 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8';
GRANT ALL PRIVILEGES ON DATABASE workshops_test to DB_USER;
GRANT ALL PRIVILEGES ON DATABASE workshops_development to DB_USER;
GRANT ALL PRIVILEGES ON DATABASE workshops_production to DB_USER;
